from selenium.webdriver.common.by import By

class PageLocators:
    SEARCH_USER_EMAIL = (By.XPATH, "//*[@id='user_email']")
    SEARCH_USER_PASSWORD = (By.XPATH, "//*[@id='user_password']")
    SEARCH_LOGIN_BUTTON = (By.XPATH, "//input[@class='btn button button__primary']")
    RESULT_BUTTON = (SEARCH_LOGIN_BUTTON)
    CREATE_STUDY = (By.XPATH, "//button[@class='ow-button ow-button--primary ow-button--medium']")
    SELECT_STUDY = (By.XPATH, "//input[@id='type']")
    STUDY_NAME = (By.XPATH, "//input[@id='name']")
    CREATE_FOLDER = (By.XPATH, "//input[@id='folder']")
    ENTER_STUDY = (By.XPATH, "//a[@href='/a/x3qqpuaf/chalkmark/surveys/d91635a1-a307-4d9d-8bc5-6e581b63b236/edit']")
    SETUP = (By.XPATH, "//button[@data-name='Setup']")
    TASK_TEXT = (By.XPATH, "//textarea[@class='ow-auto-resize-input ow-auto-resize-input--multiline ow-auto-resize-input--auto ow-input task__input']")
    TASK_IMAGE = (By.XPATH, "//div[@class='task__image']")
    TAKE_OVER = (By.XPATH, "//button[@class='ow-button ow-button--medium ow-button--secondary']")
    UPLOAD_IMAGE = (By.XPATH, "//button[@class='ow-button ow-button--small ow-button--primary']")
    SET_LAUNCH = (By.XPATH, "//button[@id='surveyLaunchButton']")
    CONFIRM_LAUNCH = (By.XPATH, "//div[@class='ow-button__text']")
    CONTROL = (By.XPATH, "//div[@class='ow-modal__footer']")
    COMPLETE_CHARGE = (By.XPATH, "//div[@id='studyApp']")
    OPEN_FOLDER = (By.XPATH, "//span[@class='studies-table__name']")
    SELECT_TEST = (By.XPATH, "//button[@class='ow-button ow-dropdown__trigger ow-dropdown studies-table__actions studies-table__actions--study ow-button--small ow-button--secondary']")
    DELETE_TEST = (By.XPATH, "//a[@data-action='delete']") 
    CONFIRM_DELETE = (By.XPATH, "//button[@class='ow-button ow-button--danger ow-button--medium']")
